.. toctree::
   :caption: Table of Contents
   :maxdepth: 2
   :name: mastertoc

.. If you are new to Crossbar.io development in general you should start here at :ref:`getting-started`

Introduction 
-------------
*  :doc:`Getting Started <pages/gettingstarted>`

Administrators
--------------
*   :doc:`Concept & Features <pages/about/Basic-Concepts>`
*   :doc:`Installation Guide <pages/installation/installation>`
*   :doc:`Administration Guide <pages/administration/Administration>`

Programmers
-----------
*   :doc:`Developer Guide <pages/programming-guide/Programming-Guide>`
*   :doc:`Integration Guide  <pages/integration-guide>`
*   :doc:`Tutorials & Recipe <pages/tutorials-recipe>`

More
----
* :doc:`Compatibility Policy  <pages/about/Compatibility-Policy>`
* :doc:`Crossbar Code License  <pages/about/Crossbar-License>`
* :doc:`Documentation License  <pages/about/Documentation-License>`
* `Contributing to the Project** <https://github.com/crossbario/crossbar/blob/master/CONTRIBUTING.md>`__
* :doc:`Contributing FAQ  <pages/about/Contributing-FAQ>`
* :doc:`FAQ  <pages/about/FAQ>`

