.. toctree::
   :caption: Table of Contents
   :maxdepth: 2
   :name: mastertoc

.. If you are new to Crossbar.io development in general you should start here at :ref:`getting-started`
Introduction 
-------------
*  :doc:`Getting Started <pages/gettingstarted>`

Administrators
--------------
*   :doc:`Concept & Features <pages/concept-features>`
*   :doc:`Installation Guide <pages/installation>`
*   :doc:`Administration Guide <pages/administration-guide>`

Programmers
-----------
*   :doc:`Developer Guide <pages/developer-guide>`
*   :doc:`Integration Guide  <pages/integration-guide>`
*   :doc:`Tutorials & Recipe <pages/tutorials-recipe>`

More
----
*   :doc:`Policy, License and more <pages/policy-licence-faq>`
* FAQ
* Contributing FAQ
