# this build argument must be defined _before_ FROM, so the value is available in FROM.
# however, CROSSBAR_ARCH will _not_ be available further down the line because of this ordering!
ARG CROSSBAR_ARCH
FROM ${CROSSBAR_ARCH}/python:3.9-slim

MAINTAINER The Crossbar.io Project <support@crossbario.com>

# these build arguments should be defined _after_ FROM, so the values are available later on
ARG CROSSBAR_BUILD_DATE
ARG CROSSBAR_VCS_REF
ARG CROSSBAR_VERSION

