objects:
	psql -d cdc -U crossbar -f upgrade_0_1_1.sql
	psql -d cdc -U crossbar -f upgrade_0_1_2.sql
	psql -d cdc -U crossbar -f upgrade_0_1_3.sql
	# psql -d cdc -U crossbar -f upgrade_0_1_4.sql
	psql -d cdc -U crossbar -f upgrade_0_1_5.sql
