###############################################################################
##
##  Copyright (C) 2014 Tavendo GmbH
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU Affero General Public License, version 3,
##  as published by the Free Software Foundation.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
##  GNU Affero General Public License for more details.
##
##  You should have received a copy of the GNU Affero General Public License
##  along with this program. If not, see <http://www.gnu.org/licenses/>.
##
###############################################################################

SVG_FILES = ['crossbar_deployment_00.svg',
             'crossbar_deployment_00b.svg',
             'crossbar_deployment_00c.svg',
             'crossbar_deployment_01.svg',
             'crossbar_deployment_02.svg',
             'crossbar_deployment_03.svg',
             'crossbar_deployment_04.svg',
             'crossbar_deployment_05.svg',
             'crossbar_deployment_06.svg',
             'crossbar_deployment_07.svg',
             'crossbar_deployment_08.svg',
             'crossbar_application_scenario_1.svg',
             'crossbar_application_scenario_2.svg',
             'crossbar_application_scenario_3.svg',
             'crossbar_application_scenario_4.svg',
             'crossbar_application_scenario_5.svg',
             'crossbar_application_scenario_6.svg',
             'crossbar_application_scenario_7.svg',
             'crossbar_transports_1.svg',
             'crossbar_transports_2.svg',
             'crossbar_clients.svg',
             'crossbar_integration.svg'
             ]

IMG_SOURCE_DIR = "figures"
IMG_GEN_DIR    = "figures/gen"


###
### Do not touch below this unless you know what you are doing;)
###

import os
import pkg_resources

taschenmesser = pkg_resources.resource_filename('taschenmesser', '..')

## use this for Taschenmesser development only
#taschenmesser = "../infrequent/taschenmesser"

env = Environment(tools = ['default', 'taschenmesser'],
                  toolpath = [taschenmesser],
                  ENV  = os.environ)


## build optimized SVGs, PNGs and gzipped versions of the former
## inside IMG_GEN_DIR
##
for svg in SVG_FILES:
   svgOpt = env.Scour("%s/%s" % (IMG_GEN_DIR, svg),
                      "%s/%s" % (IMG_SOURCE_DIR, svg),
                      SCOUR_OPTIONS = {'enable_viewboxing': True})
   env.GZip("%s.gz" % svgOpt[0], svgOpt)

   png = env.Svg2Png("%s.png" % os.path.splitext(str(svgOpt[0]))[0], svgOpt, SVG2PNG_OPTIONS = {})
   env.GZip("%s.gz" % png[0], png)
