name: crossbar
adopt-info: crossbar
summary: Crossbar.io - Polyglot application router.
description: |
  Crossbar.io is a networking platform for distributed and microservice
  applications. It is feature rich, scalable, robust and secure. Let
  Crossbar.io take care of the hard parts of messaging so you can focus
  on your app's features.

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

apps:
  crossbar:
    command: python3.7 -u $SNAP/bin/crossbar
    environment:
      PATH: $PATH:$SNAP/usr/bin:$SNAP/bin
      PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.7/site-packages
    plugs:
      - home
      - network
      - network-bind

parts:
  py37:
    plugin: nil
    stage-packages:
      - python3.7
    build-packages:
      - wget
      - python3.7
      - python3.7-dev
      - python3.7-venv
      - python3.7-distutils
    override-build: |
      snapcraftctl build
      wget -O - https://bootstrap.pypa.io/get-pip.py | /usr/bin/python3.7 -u
      /usr/bin/python3.7 -m compileall -b $SNAPCRAFT_PART_INSTALL
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.py" -exec rm {} \;
  crossbar:
    plugin: nil
    after:
      - py37
    source: .
    override-build: |
      snapcraftctl build
      # Build and install Crossbar
      export MAKEFLAGS="-j$(nproc)"
      /usr/bin/python3.7 -m pip install --ignore-installed -U --no-compile --prefix $SNAPCRAFT_PART_INSTALL .
      /usr/bin/python3.7 -m compileall -b -x .*\.syntaxerror.py$ $SNAPCRAFT_PART_INSTALL
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.py" -exec rm {} \;
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.so" -exec strip -s {} \;
      # Set package version
      snapcraftctl set-version $(git describe --always --dirty | sed -e 's/-/+git/;y/-/./' | tail -c +2)
    stage-packages:
      - libsnappy1v5
      - libunwind8
    build-packages:
      - build-essential
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev
      # required by package versioning
      - git
