name: crossbar
version: 'latest'
version-script: python3 -c "exec(open('crossbar/_version.py').read()); print(__version__)"
summary: Crossbar.io - Polyglot application router.
description: |
  Crossbar.io is a networking platform for distributed and microservice
  applications. It is feature rich, scalable, robust and secure. Let
  Crossbar.io take care of the hard parts of messaging so you can focus
  on your app's features.

grade: stable
confinement: strict
base: core18

apps:
  crossbar:
    command: crossbar
    plugs:
      - home
      - network
      - network-bind

parts:
  crossbar:
    plugin: python
    source: .
    stage-packages:
      - libsnappy1v5
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev
    override-prime: |
      snapcraftctl prime
      echo "Compiling pyc files..."
      # Delete the file that would fail the compilation process
      rm "$SNAPCRAFT_PRIME/lib/python3.6/site-packages/crossbar/worker/test/examples/syntaxerror.py"
      "$SNAPCRAFT_PART_INSTALL/usr/bin/python3" -m compileall -q "$SNAPCRAFT_PRIME"
