name: crossbar
adopt-info: crossbar
summary: Crossbar.io - Polyglot application router.
description: |
  Crossbar.io is a networking platform for distributed and microservice
  applications. It is feature rich, scalable, robust and secure. Let
  Crossbar.io take care of the hard parts of messaging so you can focus
  on your app's features.

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

apps:
  crossbar:
    command: python -u $SNAP/crossbar/bin/crossbar
    environment:
      PYTHONPYCACHEPREFIX: $SNAP_DATA/pycache
      PYTHONPATH: $PYTHONPATH:$SNAP/crossbar
      PATH: $PATH:$SNAP/crossbar/bin
    plugs:
      - home
      - network
      - network-bind

parts:
  crossbar:
    plugin: py38
    source: .
    override-build: |
      snapcraftctl build
      snapcraftctl set-version $(git describe --always --dirty | sed -e 's/-/+git/;y/-/./' | tail -c +2)
    stage-packages:
      - libsnappy1v5
      - libunwind8
    build-packages:
      - build-essential
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev
      - git

slots:
  runtime-dir:
    interface: content
    content: executables
    read:
      - $SNAP
